# Generated by Django 3.1.6 on 2021-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
